### PR TITLE
chore(README): Section about permissions

### LINKED ISSUE #55: 🐛 [BUG] - Version 1.7 requires permission to access data on all websites (Firefox)
### Pre-checks

- [X] I confirm that I am following the pre-checks

### Description

Version 1.7 requires a lot of new permissions that at first glance look **very** suspicious.

I can read from the code that clipboard, download, and tabs are related to the style import/export. It might be a good idea to add a FAQ entry explaining these permissions.

I can't see what the "all websites" permission is for though. It could be a bug, but if it's not it should also be documented.

### Reproduction steps

```bash
1. Wait for the auto update to request new permissions.
```

### Logs

```bash
N/A
```

### Browsers

Firefox

### Browser Version

130.0b5

### Anything else?

image

### PR DESCRIPTION
**Pull request by boidushya**
# Description

Section about permissions and explanation for the same

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Related Issue (if applicable)

Fixes #55 

## Checklist

- [x] I have performed a self-review of my code
- [ ] Will this be part of a product update? If yes, please write one phrase about this update.

### CODE REVIEW

**Comment by tasszz2k** [comment]
Can I continue using this extension without the new required permissions?

## Extension Permissions

| Permission                                                            | Reason                                                                                  | Data Usage                                         |
| --------------------------------------------------------------------- | --------------------------------------------------------------------------------------- | -------------------------------------------------- |
| **Read and change all your data on the websites you visit**           | Required to inject lyrics into Youtube Music page & for code editor specific JS & CSS   | No data stored                                     |
| **Get data from the clipboard**                                       | Required to import styles and themes from clipboard                                     | -                                                  |
| **Input data to the clipboard**                                       | Required to export styles and themes to clipboard                                       | -                                                  |
| **Download files and read and modify the browser's download history** | Required to download styles and themes as CSS file                                      | Does not read or modify browser's download history |
| **Access browser tabs**                                               | Required to ensure code editor works on all tabs (changes applied to Youtube Music tab) | -                                                  |

**Comment by boidushya** [comment]
Yes you can

https://github.com/boidushya/better-lyrics?tab=readme-ov-file#i-dont-like-the-new-update-can-i-revert-to-the-old-version

https://github.com/boidushya/better-lyrics?tab=readme-ov-file#chrome

https://github.com/boidushya/better-lyrics/releases/tag/v1.6.3

> Can I continue using this extension without the new required permissions?
> 
> ## Extension Permissions
> Permission	Reason	Data Usage
> **Read and change all your data on the websites you visit**	Required to inject lyrics into Youtube Music page & for code editor specific JS & CSS	No data stored
> **Get data from the clipboard**	Required to import styles and themes from clipboard	-
> **Input data to the clipboard**	Required to export styles and themes to clipboard	-
> **Download files and read and modify the browser's download history**	Required to download styles and themes as CSS file	Does not read or modify browser's download history
> **Access browser tabs**	Required to ensure code editor works on all tabs (changes applied to Youtube Music tab)	-

**Comment by tasszz2k** [comment]
Could you set these permissions to optional instead of required?

Anyone who wants to use these features can enable the corresponding permissions instead of accepting all permissions like this update.

**Comment by boidushya** [comment]
In an upcoming hotfix `v1.7.2` I'll remove the clipboardRead and clipboardWrite permissions.
I'll also try to move the downloads permission to be optional.
I'm afraid the tabs one needs to be persistent though

**Comment by tasszz2k** [comment]
because these permissions are quite critical, I am afraid that people will be concerned about the security aspect when using it.

For instance, "Read and change all your data on the websites you visit ", why isn't it the `YouTube music website` only?

**Comment by boidushya** [comment]
https://github.com/boidushya/better-lyrics?tab=readme-ov-file#extension-permissions
Explanation here ^

**Comment by tasszz2k** [comment]
sorry, but people concerned about security cannot ensure these permissions won't be used for other purposes in the future.

why don't you set them to optional? Users still have a choice to enable them to use these features.

**Comment by boidushya** [comment]
Check #57 

If you have any comments, please move to a separate issue or discord

**Pull request merged**
